// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
/** Prefer JWT anon key when publishable is the short sb_publishable_ form (more reliable for functions.invoke). */
const SUPABASE_PUBLISHABLE_KEY = (() => {
  const pub = String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "");
  const anon = String(import.meta.env.VITE_SUPABASE_ANON_KEY ?? "");
  if (pub.startsWith("eyJ")) return pub;
  if (anon.startsWith("eyJ")) return anon;
  return pub || anon;
})();

const globalForSupabase = globalThis as typeof globalThis & {
  __rasaoiSupabase?: SupabaseClient<Database>;
};

/**
 * Singleton client — Vite HMR was creating multiple GoTrueClient instances and
 * failing Navigator LockManager locks (`sb-*-auth-token`).
 */
function getClient(): SupabaseClient<Database> {
  if (globalForSupabase.__rasaoiSupabase) return globalForSupabase.__rasaoiSupabase;
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  globalForSupabase.__rasaoiSupabase = client;
  return client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getClient();
